# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUb2SFwjeUjKUqRROKYkY3Gdk9R4vGxJ
"""

# Step 1 — Mount your drive
from google.colab import drive
drive.mount('/content/drive')

# Step 2 — Export your Google Sheet as CSV first
# In Google Sheets: File → Download → CSV
# Save it to your Google Drive

# Step 3 — Load it
import pandas as pd

import numpy as np
# morocco_rainfall is based on rainfall data from https://open-meteo.com/en/docs/historical-weather-api?latitude=-7.15&longitude=31.28&start_date=1940-04-09&hourly=rain,precipitation,snowfall&temporal_resolution=hourly_6#data_sources
# snow and total precipitation (snow + rain) is not taken into account for return period calculations

df = pd.read_csv('/content/drive/MyDrive/pandas/morocco_rainfall.csv', skiprows=3)
df = df.drop(
  labels= ['Unnamed: 4', 'Unnamed: 5'],
  axis=1)
df = df.drop(
  labels= ['precipitation (mm)', 'snowfall (cm)'],
  axis=1)
df.head()

df = df.rename(columns={
    'time':         'date',
    'rain (mm)':  'rainfall_mm'
})

# --- Parse the date column ---
# format='mixed' handles the 0:00 time part automatically
df['date'] = pd.to_datetime(df['date'], format='mixed')

# --- Extract year ---
df['year'] = df['date'].dt.year

# --- Convert rainfall to numeric (removes any text/blanks) ---
df['rainfall_mm'] = pd.to_numeric(df['rainfall_mm'], errors='coerce')

# --- Drop missing values ---
df = df.dropna(subset=['rainfall_mm'])

# --- Extract annual maxima ---
annual_max = df.groupby('year')['rainfall_mm'].max()

annual_max.head()

data  = annual_max.values
n     = len(data)
mean  = np.mean(data)
sigma = np.std(data, ddof=1)

# Gumbel parameters
beta = sigma * (np.sqrt(6) / np.pi)
mu   = mean - 0.5772 * beta

# Return periods
return_periods = [10, 25, 50, 100, 200, 500]

results = []
for T in return_periods:
    y_T      = -np.log(-np.log(1 - 1/T))
    rainfall = mu + beta * y_T
    results.append({'return_period_yr': T, 'rainfall_mm': round(rainfall, 1)})

df_results = pd.DataFrame(results)
print(df_results.to_string(index=False))

from scipy.stats import genextreme
import numpy as np
import pandas as pd

data = annual_max.values

# ================================================================
# FIT GEV — scipy estimates all 3 parameters from your data
# ξ (shape), μ (location), β (scale)
# ================================================================
xi, mu, beta = genextreme.fit(data)

print(f"GEV Parameters:")
print(f"  Shape ξ:    {xi:.4f}  (0=Gumbel, >0=heavy tail, <0=bounded)")
print(f"  Location μ: {mu:.4f}")
print(f"  Scale β:    {beta:.4f}")

# ================================================================
# PREDICT FOR RETURN PERIODS
# ================================================================
return_periods = [10, 25, 50, 100, 200, 500]

results = []
for T in return_periods:
    p        = 1 - 1/T                          # non-exceedance probability
    rainfall = genextreme.ppf(p, xi, mu, beta)  # inverse CDF
    results.append({'return_period_yr': T, 'rainfall_mm': round(rainfall, 1)})

df_results = pd.DataFrame(results)
print("\nGEV Results:")
print(df_results.to_string(index=False))

print(f"\n>>> 500-year rainfall (GEV): {df_results[df_results['return_period_yr']==500]['rainfall_mm'].values[0]} mm")